[package]
name = "hyper-fs"
version = "0.1.0"
authors = ["biluohc <biluohc@qq.com>"]

[dependencies]
mxo_env_logger = "^0.1"
log = "^0.3.8"
tokio-core = "^0.1.10"
lazy_static = "^0.2.8"
futures ="^0.1.17"
poolite="^0.7.1"
hyper = "^0.11.8"
url = "^1.6.0"