[package]
name = "hyper-fs"
version = "0.1.0"
authors = ["biluohc <biluohc@qq.com>"]

[dependencies]
futures-cpupool= "0.1.7"
mxo_env_logger = "^0.1"
tokio-core = "^0.1.10"
futures ="^0.1.17"
hyper = "^0.11.8"
url = "^1.6.0"
log = "^0.3.8"